[project]
name = "seattle-weather"
version = "1.0.0"
description = "An example dashboard exploring the Seattle Weather dataset"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "pandas>=2.3.1",
    "streamlit>=1.48.1",
    "vega-datasets>=0.9.0",
]
